Feature/homework 1
ForestLamp/FocusStartHomeworks pull request #2
Opened 2021-04-22 06:34 UTC by ForestLamp

Консольное приложение, ДЗ №1.

2021-04-25 06:25 UTC, tratotul007 requested changes
Кажется фильтр не работает, и вывод всех авто что то непонятное, давай ка поправим

2021-04-25 06:25 UTC, tratotul007 commented on homework-1 console/Car.swift
> +            }
Это что такое, зачем ты проходишь циклом по всем кейфам, и все равно выводишь все кейсы?)

2021-04-25 06:25 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +        }
А сортировка то работает? я что то не вижу что б что то выводилось + зачем ты создаешь тип кузова `let _ = Car.Body(rawValue: body)` и его не используешь? тут нужно массив отфильтровать по этому значению получаенному

2021-04-26 16:40 UTC, ForestLamp commented on homework-1 console/Car.swift
> +            }
Исправил:
// Кузова для сортировки
     static func printOfBody() {
        for body in Body.allCases {
            print("\(body.rawValue) - \(body)")
            }
        }

2021-04-26 17:10 UTC, ForestLamp commented on homework-1 console/Car.swift
> +            }
Поправил, теперь все ок.
// Кузова для сортировки
     static func printOfBody() {
        for body in Body.allCases {
            print("\(body.rawValue) - \(body)")
            }
        }

2021-04-26 17:46 UTC, ForestLamp commented on homework-1 console/MainApp.swift
> +        }
func filterBodyTypes() {
        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
            else {
            assertionFailure("Ошибка при сортировке, введите число")
            return
        }
    }

2021-04-26 17:51 UTC, ForestLamp commented
Исправил замечания

2021-04-27 09:38 UTC, tratotul007 requested changes

2021-04-27 09:38 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
Фильтр все так и не работает, точнее наверное работает, но как это понять? ты сам тестировал? отсортировало?)

2021-04-27 09:38 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
и зачем ты в strongReadLine() который и так у тебя выведет текст запринтит его, еще пихаешь один принт??

2021-04-27 09:38 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
func strongReadLine(_ text: String) -> String {
         print(text)

2021-04-27 09:39 UTC, tratotul007 commented on homework-1 console/Car.swift
> +        static func printOfBody() {
и метод не притОфБоди, а printAllBodies тогда уж

2021-04-27 09:41 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +        guard let body = Int(self.strongReadLine("Выберите тип кузова: \(print(Car.Body.printOfBody()))")), let chooseBody = Car.Body(rawValue: body) else {
и здесь тоже, у тебя принт(принт( и принтОфБоди тоже делает принт))

2021-04-27 09:41 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +                self.filterBodyTypes()
Ну и что приложка у нас выйдет после пунка меню 3?

2021-04-27 09:42 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +                self.filterBodyTypes()
после филтрации?

2021-04-27 13:12 UTC, ForestLamp commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
Ошибка не возникает, когда выбираешь фильтр и любой номер приложение выходит... Надо вывести список авто с этим кузовом после сортировки?

2021-04-27 17:09 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
В том то и дело что ошибка не возникает, но оно и не фильтрует никак по моему...

2021-04-27 17:12 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
Где сортировка то? после какой сортировки ты собираешься выводить `список авто с этим кузовом` ? ну и после ее конечно надо вывести, иначе зачем бы она нужна была эта сортировка)

2021-04-27 17:14 UTC, tratotul007 commented on homework-2/homework-2/ViewController.swift
> +class ViewController: UIViewController {
А что в ЭТОМ коммите ты сделал с сортировкой ??

2021-04-28 06:56 UTC, ForestLamp commented on homework-1 console/Car.swift
> +        static func printOfBody() {
Согласен, исправил

2021-04-28 06:58 UTC, ForestLamp commented on homework-1 console/MainApp.swift
> +        guard let body = Int(self.strongReadLine("Выберите тип кузова: \(print(Car.Body.printOfBody()))")), let chooseBody = Car.Body(rawValue: body) else {
Исправил.

2021-04-28 06:59 UTC, ForestLamp commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
Спасибо, исправил!

2021-04-28 07:02 UTC, ForestLamp commented on homework-2/homework-2/ViewController.swift
> +class ViewController: UIViewController {
Пока я разбирался с гитхабом я жутко начудил, поэтому сори если со стороны это выглядит дико.

2021-04-28 14:52 UTC, ForestLamp commented on homework-1 console/MainApp.swift
> +        guard Int(strongReadLine("По какому кузову отсортировать? \(print(Car.Body.printOfBody()))")) != nil
Подчинил, теперь сортируется и выводится!

    func filterBodyTypes() {
        guard let body = Int(strongReadLine("По какому кузову отсортировать? \(Car.Body.printAllBodies())")), let chooseBody = Car.Body(rawValue: body) else {
            assertionFailure("Ошибка при сортировке, введите число")
            return
        }
        for car in cars {
            if car.body.rawValue == chooseBody.rawValue {
                print(car) } else {
                    print("Машин с таким кузовом нет.")
                    self.start()
                }
        }
    }

2021-04-28 14:53 UTC, ForestLamp commented on homework-1 console/MainApp.swift
> +                self.filterBodyTypes()
Разобрался, теперь работает.

2021-04-28 14:53 UTC, ForestLamp commented
Все исправил, теперь сортировка работает, и отсортированные машины по кузову выводятся.

2021-04-29 04:42 UTC, tratotul007 commented on homework-1 console/Car.swift
> +    var body: Body
Зачем вар??

2021-04-29 04:43 UTC, tratotul007 commented on homework-1 console/MainApp.swift
>          guard let body = Int(self.strongReadLine("Выберите тип кузова: \(Car.Body.printAllBodies())")), let chooseBody = Car.Body(rawValue: body) else {
Ниже починил гуард, а тут забыл?

2021-04-29 04:44 UTC, tratotul007 commented on homework-1 console/Car.swift
> +
Видишь что добавлено пустое место? пустая строка может быть, а пробелы убери

2021-05-01 05:09 UTC, ForestLamp commented on homework-1 console/Car.swift
> +    var body: Body
Исправил

2021-05-01 05:18 UTC, ForestLamp commented on homework-1 console/MainApp.swift
>          guard let body = Int(self.strongReadLine("Выберите тип кузова: \(Car.Body.printAllBodies())")), let chooseBody = Car.Body(rawValue: body) else {
Тут все работает...

2021-05-01 05:18 UTC, ForestLamp commented on homework-1 console/Car.swift
> +
Сделал

2021-05-01 05:21 UTC, ForestLamp commented
Внес правки, в первом гуарде не понял если честно в чем ошибка, при запуске все работает.

2021-05-01 05:46 UTC, tratotul007 commented on homework-1 console/MainApp.swift
> +                    self.start()
А почему все старты в свиче, а этот тут?

2021-05-01 09:49 UTC, lsgsk commented
Привет, добавь в описание профиля ФИО

2021-05-04 06:25 UTC, ForestLamp commented on homework-1 console/MainApp.swift
> +                    self.start()
Я решил так сделать что бы при выборе несуществующего кузова приложение не выходило а перезапускалось.

2021-05-04 06:28 UTC, ForestLamp commented
> Привет, добавь в описание профиля ФИО

Добавил в "bio" профиля.

2021-05-04 06:35 UTC, tratotul007 approved these changes

2021-05-04 06:35 UTC, merged